#!/bin/bash

python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/150_UCR_Anomaly_Lab2Cmac011215EPG6_7000_12190_12420.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/151_UCR_Anomaly_MesoplodonDensirostris_10000_19280_19440.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/152_UCR_Anomaly_PowerDemand1_9000_18485_18821.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/157_UCR_Anomaly_TkeepFirstMARS_3500_5365_5380.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/159_UCR_Anomaly_TkeepSecondMARS_3500_9330_9340.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/162_UCR_Anomaly_WalkingAceleration5_2700_5920_5979.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/163_UCR_Anomaly_apneaecg2_10000_20950_21100.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/166_UCR_Anomaly_apneaecg_10000_12240_12308.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/167_UCR_Anomaly_gait1_20000_38500_38800.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/170_UCR_Anomaly_gaitHunt1_18500_33070_33180.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 2 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/174_UCR_Anomaly_insectEPG2_3700_8000_8025.out