#!/bin/bash

python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/176_UCR_Anomaly_insectEPG4_1300_6508_6558.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/179_UCR_Anomaly_ltstdbs30791AS_23000_52600_52800.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/180_UCR_Anomaly_ltstdbs30791ES_20000_52600_52800.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/181_UCR_Anomaly_park3m_60000_72150_72495.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/182_UCR_Anomaly_qtdbSel1005V_4000_12400_12800.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/183_UCR_Anomaly_qtdbSel100MLII_4000_13400_13800.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/186_UCR_Anomaly_resperation1_100000_110260_110412.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/192_UCR_Anomaly_s20101mML2_12000_35774_35874.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/193_UCR_Anomaly_s20101m_10000_35774_35874.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/194_UCR_Anomaly_sddb49_20000_67950_68200.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 1 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/195_UCR_Anomaly_sel840mECG1_17000_51370_51740.out