#!/bin/bash

python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/109_UCR_Anomaly_1sddb40_35000_52000_52620.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/112_UCR_Anomaly_BIDMC1_2500_5400_5600.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/115_UCR_Anomaly_CIMIS44AirTemperature3_4000_6520_6544.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/117_UCR_Anomaly_CIMIS44AirTemperature5_4000_4852_4900.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/120_UCR_Anomaly_ECG2_15000_16000_16100.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/121_UCR_Anomaly_ECG3_15000_16000_16100.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/130_UCR_Anomaly_GP711MarkerLFM5z4_4000_6527_6645.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/131_UCR_Anomaly_GP711MarkerLFM5z5_5000_8612_8716.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/140_UCR_Anomaly_InternalBleeding4_1000_4675_5033.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/141_UCR_Anomaly_InternalBleeding5_4000_6200_6370.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 0 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/149_UCR_Anomaly_Lab2Cmac011215EPG5_7000_17390_17520.out