#!/bin/bash

python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/196_UCR_Anomaly_sel840mECG2_20000_49370_49740.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/198_UCR_Anomaly_tiltAPB2_50000_124159_124985.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/199_UCR_Anomaly_tiltAPB3_40000_114000_114370.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/205_UCR_Anomaly_CHARISfive_9812_28995_29085.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/207_UCR_Anomaly_CHARISten_3165_26929_26989.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/209_UCR_Anomaly_Fantasia_19000_26970_27270.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/212_UCR_Anomaly_Italianpowerdemand_8913_29480_29504.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/223_UCR_Anomaly_mit14046longtermecg_74123_131200_131700.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/226_UCR_Anomaly_mit14046longtermecg_96123_123000_123300.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/242_UCR_Anomaly_tilt12744mtable_100000_104630_104890.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/244_UCR_Anomaly_tilt12754table_100013_104630_104890.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/248_UCR_Anomaly_weallwalk_2000_4702_4707.out
python3 scripts/finetuning/anomaly_detection.py --config configs/anomaly_detection/linear_probing.yaml --gpu_id 3 --finetuning_mode linear-probing --dataset_names /TimeseriesDatasets/anomaly_detection/TSB-UAD-Public/KDD21/250_UCR_Anomaly_weallwalk_2951_7290_7296.out